
format = """
[░▒▓](#a3aed2)\
[󰣇 ](bg:#a3aed2 fg:#394260)\
$directory\
[▓▒░](bg:#394260 fg:#769ff0)\
$git_branch\
$git_status\
[▓▒░](bg:#1d2230 fg:#394260)\
$time\
[▓▒░](fg:#1d2230)\
\n$character"""


#(bg:#1d2230 fg:#394260)
right_format = """
[░▒▓](fg:#394260)\    
$c\
$dart\
$deno\
$dotnet\
$golang\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$zig\
$memory_usage\
[░▒▓](bg:#394260 fg:#769ff0)\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
[░▒](bg:#769ff0 fg:#a3aed2)\
$battery\
$sudo\
[▓▒░](#a3aed2)""" # [▓▒░](fg:#1d2230)\format = """


[sudo]
disabled = false
symbol = ' '
style = "bg:#a3aed2 fg:#090c0c"
format = "[$symbol]($style)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold light blue)"
disabled = false

[memory_usage]
symbol = ""
format = '$symbol [${ram}( | ${swap})]($style)'


[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green bg:#a3aed2)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red bg:#a3aed2"

[[battery.display]]
threshold = 60
style = "italic dimmed black bg:#a3aed2"

[[battery.display]]
threshold = 70
style = "italic dimmed black bg:#a3aed2"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](bg:#394260 fg:#769ff0)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](bg:#394260 fg:#769ff0)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[python]
symbol = ''
style = "bg:#394260"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[deno]
symbol = ''
style = "bg:#394260"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[dart]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[c]
symbol = ''
style = "bg:#212736"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[java]
symbol = ''
style = "bg:#212736"
format = '[[ $symbol ($version) ](bg:#394260 fg:#769ff0)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
