[general]
import = ["~/.config/alacritty/themes/tokyo_night.toml"]
[font]
normal = { family = "Hack", style = "Regular" }
size = 14

[colors.primary]
foreground = '#00ffff'
background = '#000000'

[window]
opacity = 0.12
